name: ci

on:
  push:

jobs:
  dockerbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/webapp:latest

  deployment:
    runs-on: ubuntu-latest
    needs:
      - dockerbuildpush
    steps:
      - name: Deploy to Azure server
        run: |
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem azureuser@52.186.174.4 << EOF
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/webapp:latest
            docker stop webapp || true
            docker rm webapp || true
            docker run -d --name webapp -p 80:80 ${{ vars.DOCKERHUB_USERNAME }}/webapp:latest
          EOF